name: Deploy
on:
  push:
    branches:
      - main

jobs:
  npm-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm ci

      - name: Run your npm command
        run: npm run deploy # Replace 'your-command' with your specific npm command
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
